### ISSUE TITLE
GSoC - Casbin-CPP (Divy Patel)

### ISSUE THREAD

**Issue by hsluoyz** [casbin/SummerOfCode2020#10]
GSoC Project: https://summerofcode.withgoogle.com/projects/#5002012883681280

![image](https://user-images.githubusercontent.com/3787410/83535522-9bd42a00-a524-11ea-9e6b-b2adb2491a79.png)

Student: @divy9881

Mentors: @xcaptain @nodece @techoner @hsluoyz 

IM Channel: https://hangouts.google.com/group/pi339FCTHfnUAZws8

Weekly reports will be appended as replies by the student.

**Comment by DivyPatel9881** [comment]
## Weekly Report 1
**Completed Work:**
1. **Config**
    - Implement interface `ConfigInterface` and class `Config`
2. **Effect**
    - Implement interface `Effector` and class `DefaultEffector`
3. **Model**
    - Implement class `Assertion`, class `Model` and class `FunctionMap`
    - Implement duktape utility functions for expression parsing and evaluation
    - Implement `BuildIncrementalRoleLinks` method in class `Assertion`
4. **Persist**
    - Implement interface `Adapter`, interface `FilteredAdapter`, class `FileAdapter` and class `FilteredAdapter`
    - Implement interface 'Watcher' and basic skeleton of class `DefaultWatcher`
    - Implement batch adapter policy rules feature by implementing interface 'BatchAdapter' and class 'BatchFileAdapter'
    - Implement interface `WatcherEx` and basic skeleton of class `DefaultWatcherEx`
5. **RBAC**
    - Implement interface `RoleManager`, class `DefaultRoleManager`, class `Role` and class `GroupRoleManager`
6. **Utility functions for Casbin-CPP implementation**
7. **Enforcer**
    - Implement interface `EnforcerInterface` and class `Enforcer`
8. **API**
    - Implement `management_api`, `internal_api`, `rbac_api` and `rbac_api_with_domains`
***
**Work in Progress:**
1. **Config**
    - Write TestSuites for `Config`
2. **Effect**
    - Write TestSuites for `Effect`
    - Implement `Quick Return` feature
3. **Model**
    - Write TestSuites for `Model`
4. **Persist**
    - Write TestSuites for `Persist`
5. **RBAC**
    - Write TestSuites for `RBAC`
6. **Util**
    - Write TestSuites for `Util`
7. **Enforcer**
    - Write TestSuites for `Enforcer`
    - Implement `SyncedEnforcer` and `CachedEnforcer`
8. **API**
    - Write TestSuites for `management_api`, `internal_api`, `rbac_api` and `rbac_api_with_domains`
9. **Log, Exception and Error**
    - Implement `Log`, `Exception` and `Error` modules

**Comment by divy9881** [comment]
## Weekly Report 2 [ 08-06-2020 to 14-06-2020 ] (dd-mm-yyyy)
**Completed Work:**
1. **Config**
    - Write TestSuites for `Config`
2. **Model**
    - Write TestSuites for `Model`
3. **Code formatting**
    - The code implementation was separated in `.h` and `.cpp` files. The `class` and `function declarations`in `.h` files and their implementation in `.cpp` files.
    - Follow the `Google Guide` for writing `C++` code. The file names, class names, function names and member variable names were updated according to the guide.
4. **Linker issues**
    - Fix the C++ linker build errors.
5. **Set-Up build workflow on VS 2019 C++**
    - Set-Up build workflow on `Microsoft Visual Studio 2019`. The configurations were updated to generate `.lib` file which can now be used in other projects successfully.
***
**Work in Progress:**
1. **Set-Up Azure Pipeline**
    - Set-Up `Azure` pipeline for `C++ build and testing CI`.
2. **Improve build**
    - Improve `import file` functionality to enhance system build compatibility. 
3. **Effect**
    - Write TestSuites for `Effect`
    - Implement `Quick Return` feature
4. **Persist**
    - Write TestSuites for `Persist`
5. **RBAC**
    - Write TestSuites for `RBAC`
6. **Util**
    - Write TestSuites for `Util`
7. **Enforcer**
    - Write TestSuites for `Enforcer`
    - Implement `SyncedEnforcer` and `CachedEnforcer`
8. **API**
    - Write TestSuites for `management_api`, `internal_api`, `rbac_api` and `rbac_api_with_domains`
9. **Log, Exception and Error**
    - Implement `Log`, `Exception` and `Error` modules
10. **Update README**
    - Update the `README` with more description about `setup` and `installation` details. Update the `API` details of casbin C++ library.

PR : https://github.com/casbin/casbin-cpp/pull/16

**Comment by divy9881** [comment]
## Weekly Report 3 [ 15-06-2020 to 21-06-2020 ] (dd-mm-yyyy)
**Completed Work:**
1. **Set-Up Azure Pipeline**
    - Set-Up `Azure` pipeline for `C++ build and testing CI`.
2. **Improve build**
    - Improve `import file` functionality to enhance system build compatibility. 
3. **Add README**
    - Add README description of casbin-cpp repository
4. **Util**
    - Write TestSuites for `Util`
5. **Explore C++ project environments**
    - Exploring other C++ projects for setting up build and test workflow for casbin-cpp to ensure support on multiple platforms.
***
**Work in Progress:**
1. **Effect**
    - Write TestSuites for `Effect`
    - Implement `Quick Return` feature
2. **Persist**
    - Write TestSuites for `Persist`
3. **RBAC**
    - Write TestSuites for `RBAC`
4. **Enforcer**
    - Write TestSuites for `Enforcer`
    - Implement `SyncedEnforcer` and `CachedEnforcer`
5. **API**
    - Write TestSuites for `management_api`, `internal_api`, `rbac_api` and `rbac_api_with_domains`
6. **Log, Exception and Error**
    - Implement `Log`, `Exception` and `Error` modules
7. **Update README**
    - Update the `README` with more description about `setup` and `installation` details. Update the `API` details of casbin C++ library.

**Comment by divy9881** [comment]
## Weekly Report 4 [ 22-06-2020 to 28-06-2020 ] (dd-mm-yyyy)
**Completed Work:**
1. **Set-Up Semantic-Release**
    - Set-Up `Semantic-Release` for `casbin-cpp`.
2. **Built-In-Functions**
    - Write TestSuites for `built-in-functions`
    - Change the logic of KeyMatch<n> functions from regex to ad-hoc
3. **RBAC**
    - Write TestSuites for `RBAC`
4. **Fix iteration for vectors**
    - Change iteration logic of vectors from iterators to index based iteration
***
**Work in Progress:**
1. **Effect**
    - Write TestSuites for `Effect`
    - Implement `Quick Return` feature
2. **Persist**
    - Write TestSuites for `Persist`
3. **Enforcer**
    - Write TestSuites for `Enforcer`
    - Implement `SyncedEnforcer` and `CachedEnforcer`
4. **API**
    - Write TestSuites for `management_api`, `internal_api`, `rbac_api` and `rbac_api_with_domains`
5. **Set-up build for linux**
     - Set-up the project build for Unix to enable support on Linux and MacOS machines
6. **Log, Exception and Error**
    - Implement `Log`, `Exception` and `Error` modules
7. **Update README**
    - Update the `README` with more description about `setup` and `installation` details. Update the `API` details of casbin C++ library.

**Comment by hsluoyz** [comment]
Closed as completed.
