### ISSUE TITLE
Please submit 2nd weekly reports

### ISSUE THREAD

**Issue by hsluoyz** [casbin/SummerOfCode2020#13]
@divy9881 @kingiw Please submit 2nd weekly reports: https://github.com/casbin/SummerOfCode2020/issues

@hackerchai you seem to have missed the 1st weekly report also, please submit 1st and 2nd weekly report.

**Comment by divy9881** [comment]
this issue has been fixed, hence can be closed now.

**Comment by hsluoyz** [comment]
OK.

**Comment by hsluoyz** [comment]
BTW, @divy9881 @kingiw @hackerchai time to submit 3rd report.

**Comment by divy9881** [comment]
Yes, I am currently working on that.

**Comment by hackerchai** [comment]
I am getting into it.

**Comment by kingiw** [comment]
Got it, and I'll finish it asap
