### ISSUE TITLE
Call for GSoC mentors!

### ISSUE THREAD

**Issue by hsluoyz** [casbin/SummerOfCode2020#3]
Currently, all Casbin maintainers are:

- Go: @nodece @BetaCat0 
- Java: @fangzhengjin 
- Nodejs: @chalince @ghaiklor @calebfaruki
- PHP: @techoner 
- Python: @techoner 
- .NET: @huazhikui 
- Delphi: @jkour 
- Rust: @GopherJ @xcaptain 

Thanks for your long-time contribution!

As you know, Casbin has been selected as mentoring org for Google Summer of Code. Now Google requires me to collect idea list for GSoC and the corresponding mentors. I would like to see at least one mentor could volunteer for each language. So I formally request that if you have time and interest to be a mentor of Casbin for GSoC this summer, please comment in this thread. Thanks!

We are still very short of mentors. Currently, only @techoner and @GopherJ agreed to be mentor. So please volunteer !

Note:

1. Not every idea will be chosen. Our number of slots is determined by Google.
2. I simply get the above list from git commits. If you are not in the list but are familiar with Casbin, please also join us !

**Comment by calebfaruki** [comment]
Would be interested. Client-side casbin-js lib sounds like a good one. But open to working on other ideas or coming up with one of my own.

**Comment by hsluoyz** [comment]
@calebfaruki thanks! I have updated the mentor here: https://github.com/casbin/SummerOfCode2020#casbinjs

**Comment by jkour** [comment]
Hi,
what is a mentor supposed to do?

**Comment by hsluoyz** [comment]
Hi @jkour , quote from: https://google.github.io/gsocguides/mentor/

`
Mentor: Mentors are people from the community who volunteer to work with a student. Mentors provide guidance such as pointers to useful documentation, code reviews, etc. In addition to providing students with feedback and pointers, a mentor acts as an ambassador to help student contributors integrate into their project’s community. Some organizations choose to assign more than one mentor to each of their students. Many members of the community provide guidance to their project’s GSoC students without mentoring in an “official” capacity, much as they would answer anyone’s questions on the project’s mailing list or IRC channel.
`

In my own wording,

1. Provide an idea for student to work on, and the roadmap. You can think about what to do next about Casbin4D and let the student do it for you.
2. At summer (3 months), sync with him, maybe routinely one time a week with an IM or voice/video meeting if you like. Make sure he is still on the track.
3. Evaluate his work for mid-term and the end, based on whether he actually contributes something to Casbin4D.

**Comment by ghaiklor** [comment]
It's a great idea, I support it.

Unfortunately I will not have time for it, I'm on a full-time contract at the moment. So that, I must pass here.

**Comment by hsluoyz** [comment]
@ghaiklor understood.

**Comment by jkour** [comment]
Please put me down as mentor for Delphi. TBH I can't figure out at the moment what sort of commitment is needed but I find it interesting so let's support Casbin

:-)

**Comment by hsluoyz** [comment]
@jkour Thanks for supporting! Please add your idea to the README by sending a PR.

**Comment by liuchangyan** [comment]
I am super willing to contribute my ideas to yout project~

**Comment by hsluoyz** [comment]
@xcaptain do you have interest to be the Casbin C/C++ mentor (if we have a slot for it)?

**Comment by zhuangabilitist** [comment]
I am Chen Zibo From BUPT,I hava delivered my CV by email.I am eager to join your GSoC project.

**Comment by zhuangabilitist** [comment]
I am Chen Zibo from BUPT,i have seen your post in bbs.byr and delivered my cv by email.I am eager to join your GSoC project as a student.

**Comment by hsluoyz** [comment]
Hi @zhuangabilitist , I think maybe you can get a better name. Then contribute to an idea!

**Comment by zhuangabilitist** [comment]
@hsluoyz  Is my name difficult to read?I will get a new name.
I want to join the project "Casbin for C++",so should I make a demo or write a  sample of application framework?

**Comment by hsluoyz** [comment]
It's not formal :)

See C++'s repo issues.

**Comment by Sagar2366** [comment]
Hi @hsluoyz , I would be happy to guide and mentor for Python, Nodejs and Java project during this Gsoc2020. Ready to give time to help students to contribute for this project.

Please send me mentor invite on : sagarutekar2366@gmail.com

Thanks.
Sagar Utekar

**Comment by hsluoyz** [comment]
@Sagar2366 thanks for your interest! Can you tell me a little bit about how you know or use Casbin?

**Comment by Sagar2366** [comment]
@hsluoyz , I am an Open Source Enthusiast and thus keep on learning and exploring many open source projects. I come across Casbin project recently - it has nice features for RBAC, ABAC, set of API's, very simple and easily understandable documentation.

As my experience with Python, Node.js, Java, I would like to mentor for those libraries. It will give me opportunity to learn and help GSoC student.

Also I am good with Docker, Kubernetes, Jenkins, Terraform, OpenStack, other devops tools and cloud (AWS, GCP, Azure) - I will try to suggest and add more features to the project while mentoring.

**Comment by Sagar2366** [comment]
@hsluoyz , Would you like to comment on this ?

**Comment by hsluoyz** [comment]
Hi @Sagar2366 , it looks good. I think Python and Java still require mentors. Can you start to engage the issues, interact with PRs and students?

**Comment by Sagar2366** [comment]
@hsluoyz , How can I update my name in Python and Java projects ? Also, can you please send me GSoC mentor invitation on sagarutekar2366@gmail.com ?

**Comment by hsluoyz** [comment]
@Sagar2366 If it's OK, I'd like to see more about how you interact in Casbin community before an invitation. I think there's no deadline for GSoC mentors? at least in one month?

**Comment by Sagar2366** [comment]
Ok. Thank you.

**Comment by hsluoyz** [comment]
@fangzhengjin @calebfaruki @jkour @GopherJ can you provide me your Emails, so I can add you to GSoC mentors?

**Comment by Rahul-Devhub** [comment]
Hello Casbin, I am Interested to be a mentor for Google Summer of Code 2021. I will able to commit 100 - 120 Hours in the upcoming 3 - 5 Months.

**Comment by hsluoyz** [comment]
@Rahul-Devhub plz send issue to: https://github.com/casbin/SummerOfCode2021

This repo is only for GSoC 2020.
