### ISSUE TITLE
The workload is not enough to implement only 3 adapters for Node-Casbin's idea

### ISSUE THREAD

**Issue by hsluoyz** [casbin/SummerOfCode2020#6]
Actually, if it's a common DB like MySQL, I can finish one adapter in one day. But GSoC lasts for 3 months. We need to put more development content into this idea.

https://github.com/casbin/SummerOfCode2020#ideas-1

@nodece what do you think?

**Comment by Marvin9** [comment]
I strongly agree with that. First time, developing Postgre Adapter I thought It is easier and require less time for all 3 Adapters. 

Possible alternatives I thought were

1. Supporting more adapters.
2. Adding system test. May be possible cases were data is large & more transactitons are there. We can test adapter's performance based on that. This can be challanging. 

I'm interested in this discussion. @hsluoyz @nodece

**Comment by hsluoyz** [comment]
@Marvin9 Thanks for supporting it. This is fixed by PR: https://github.com/casbin/SummerOfCode2020/pull/8

We can follow the issues provided by @nodece on: https://github.com/casbin/node-casbin/issues for more workloads.
